### ISSUE TITLE
Possible direction for windows version

### ISSUE THREAD

**Issue by denisfitz57** [yaxu/feedforward#10]
I have managed to make a running version of feedforward by installing it under the [WSL 2](https://docs.microsoft.com/en-us/windows/wsl/wsl2-index) (Windows Subsystem of Linux).  My edition is Windows 10 Pro Insider Preview 19603.1000 with Ubuntu 18.04 LTS as the linux distribution I'm using.

When I say running, I've managed to see the colored cursors cycle over the top of the current sound strings.  No sounds - I didn't try installing supercollider within the WSL distribution- there are plentiful warnings about trying to get sound going under the WSL.  I would most like to communicate with the Supercollider running in Windows, which I have every reason to believe is possible.  

I'll need to figure out what ip address to use for windows, maybe how to permit things going through the firewall.  Googling gives guidance on that, but solving the next section would help pruning the debug tree, as my network understanding is not what it needs to be. 

I could most use help on where I might insert this new address in the feedforward and/or tidal code.  Ideally it would be a line in a config file.
Also, Alt-Enter is used to toggle full screen in the WSL terminal, so how to substitute a different key combo for that would also be helpful
![feedforward](https://user-images.githubusercontent.com/1459124/79289269-6ef18800-7e8e-11ea-83f7-6ce4c043c908.png)
.

**Comment by yaxu** [comment]
Hi, sorry I missed this.. searching for 127.0.0.1 would find the location of the IP address. I think ctrl-x is already an alias for alt-enter.
