### ISSUE TITLE
Install instructions are incomplete

### ISSUE THREAD

**Issue by mtift** [yaxu/feedforward#2]
I was unable to install this on Debian GNU/Linux 9.4 (stretch). Using `cabal-install version 1.24.0.1`. This is what I see when I try `cabal install`:

```
cabal: Error reading local package.
Couldn't find .cabal file in: .
```

The README says to install with `cabal install` but there isn't a .cabal file. I tired to make one with `cabal init`, but that didn't work. When I run `cabal install -v3`, I see statement such as:

```
Searching for alex in path.
Cannot find alex on the path
...
Searching for greencard in path.
Cannot find greencard on the path
...
Searching for happy in path.
Cannot find happy on the path
```

I'm quite new to Haskell, but is there something obvious I'm missing?

**Comment by yaxu** [comment]
Apologies, have added the missing file now. You can also run it without compiling, just by doing `runhaskell Main 2>error.txt`

**Comment by mtift** [comment]
Thanks for the file. Unfortunately, neither of those approaches work. libncurses5-dev is installed ([6.0+20161126-1+deb9u2](https://packages.debian.org/stretch/libncurses5-dev)), but running `cabal install` ends with this message:

```
cabal: Error: some packages failed to install:
feedforward-0.1.0.0 depends on ncurses-0.2.16 which failed to install.
ncurses-0.2.16 failed during the configure step. The exception was:
ExitFailure 1
```

I tried running using cabal to install happy, alex, c2hs, and then ncurses, but that also resulted in errors about "Missing C libraries: panelw, ncursesw." So I tried installing libncursesw5-dev, but also no dice.

I'll keep exploring.

**Comment by yaxu** [comment]
Ah sorry I forgot about the additional dependencies, but I think installing libncursesw5-dev should have provided panelw/ncursesw. Are you still getting the same error?

**Comment by mtift** [comment]
Yeah, with `libncursesw5-dev` I tried `cabal install`, but it complained about c2hs

```
cabal: The program 'c2hs' version >=0.15 is required but it could not be found.
```

I tried `cabal install c2hs` and then try `caball install` again, but get a strange error about an extra semi-colon:

```
cabal install
Resolving dependencies...
Configuring ncurses-0.2.16...
Building ncurses-0.2.16...
Failed to install ncurses-0.2.16
Build log ( /home/mtift/.cabal/logs/ncurses-0.2.16.log ):
cabal: Entering directory '/tmp/cabal-tmp-16649/ncurses-0.2.16'
Configuring ncurses-0.2.16...
Building ncurses-0.2.16...
Preprocessing library ncurses-0.2.16...
c2hs: C header contains errors:

/usr/include/x86_64-linux-gnu/bits/floatn.h:87: (column 29) [ERROR]  >>> Syntax error !
  The symbol `;' does not fit here.

cabal: Leaving directory '/tmp/cabal-tmp-16649/ncurses-0.2.16'
cabal: Error: some packages failed to install:
feedforward-0.1.0.0 depends on ncurses-0.2.16 which failed to install.
ncurses-0.2.16 failed during the building phase. The exception was:
ExitFailure 1
```

And that all seems suspicious because the only file in my `~/.cabal/bin` directory is c2hs and there are files in `~/.cabal/packages/hackage.haskell.org/c2hs/0.28.3$`.

My suspicion is that I should not have run `cabal install c2hs`, but that's just a guess.

**Comment by willbasky** [comment]
If you have `stack`  (and Linux) you can install feedforward with
`stack ghc Main.hs`
for missing libs 
`stack install missingLib`
and again
`stack ghc Main.hs`
after successful installation run program with `./Main`

**Comment by yaxu** [comment]
You were right to install c2hs, it seems there is a bug (https://github.com/haskell/c2hs/issues/192). But hopefully stack helps you here as @willbasky suggests..

**Comment by mtift** [comment]
Thanks for all of the suggestions. Unfortunately, it still doesn't work.

First, i tried the `haskell-stack` package that comes with Debian: https://packages.debian.org/stretch/haskell-stack. Running `stack ghc Main.hs` resulted in this error:

`Downloaded lts-11.11 build plan.`

`AesonException "Error in $.packages.cassava.constraints.flags: failed to parse field packages: failed to parse field constraints: failed to parse field flags: Invalid flag name: \"bytestring--lt-0_10_4\""`

So I uninstalled that and installed the latest version of stack following the generic directions: 

https://docs.haskellstack.org/en/stable/install_and_upgrade/

Running `stack ghc Main.hs` concludes with this error:

```
<no location info>: error: can't find file: Main.hs
```

Running `stack install missingLib` results in this error:

```
stack install missingLib`

Warning: /home/mtift/bin/feedforward/feedforward.cabal was modified manually. Ignoring /home/mtift/bin/feedforward/package.yaml in favor of the cabal file. If you want to use the package.yaml file instead of the cabal file, then please delete the cabal file.

Error: While constructing the build plan, the following exceptions were encountered:

Unknown package: missingLib
```

And running `stack ghc Main.hs` results in this error:

```
[1 of 4] Compiling Change           ( Change.hs, Change.o )

Change.hs:5:1: error:
    Could not find module ‘Data.Aeson’
    Perhaps you meant Data.Version (from base-4.10.1.0)
    Use -v to see a list of the files searched for.
  |
5 | import qualified Data.Aeson   as A
```

**Comment by willbasky** [comment]
> Running stack ghc Main.hs concludes with this error:

The command executes from directory where `Main.hs` is.

> Running stack install missingLib results in this error:

`missingLib` should to be replaced with missed module))

> Could not find module ‘Data.Aeson’

In the case, for example, `stack instal aeson`

**Comment by mtift** [comment]
That makes more sense. I stack installed aeson, hint, tidal, and ncurses. However, I just ended up with the same ncurses ssemi-colon error as before:

```
stack install ncurses
ncurses-0.2.16: configure
ncurses-0.2.16: build

--  While building custom Setup.hs for package ncurses-0.2.16 using:
      /home/mtift/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_2.0.1.0_ghc-8.2.2 --builddir=.stack-work/dist/x86_64-linux/Cabal-2.0.1.0 build --ghc-options " -ddump-hi -ddump-to-file -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
    Logs have been written to: /home/mtift/bin/feedforward/.stack-work/logs/ncurses-0.2.16.log

    Configuring ncurses-0.2.16...
    Preprocessing library for ncurses-0.2.16..
    c2hs: C header contains errors:
    
    /usr/include/x86_64-linux-gnu/bits/floatn.h:87: (column 29) [ERROR]  >>> Syntax error !
      The symbol `;' does not fit here.
```

So I'm guessing you guys must be using a newer or older version of ncurses, or gcc7.

**Comment by yaxu** [comment]
@mtift Your problems seem to be related to a particular version of glibc https://github.com/haskell/c2hs/issues/192

**Comment by yaxu** [comment]
@willbasky has contributed a .stack file, building with that I see there is a problem with loading modules to run Tidal. Looking at it now..

**Comment by yaxu** [comment]
@willbasky Both cabal and stack are working for me now.. but I seem to have messed things up by editing the `feedforward.cabal` rather than `stack.yaml`file. What should I have done?

**Comment by willbasky** [comment]
@yaxu You should delete `.cabal` file and edit only `stack.yaml` and `package.yaml` files. `Package.yaml` will autogenerate `.cabal` file.
