### ISSUE TITLE
cabal v1-install fails after tidal-1.7.1 update

### ISSUE THREAD

**Issue by ndr-brt** [yaxu/feedforward#25]
With `cabal v1-install` I get this error:
```
<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your .cabal file's other-modules: 
        Code Parameters
[6 of 7] Compiling Edit             ( src/Edit.hs, dist/build/feedforward/feedforward-tmp/Edit.o )

src/Edit.hs:526:41: error:
    Ambiguous occurrence ‘resolve’
    It could refer to
       either ‘Sound.Tidal.Context.resolve’,
              imported from ‘Sound.Tidal.Context’ at src/Edit.hs:30:1-54
              (and originally defined in ‘Sound.Tidal.Stream’)
           or ‘Edit.resolve’, defined at src/Edit.hs:533:1
    |
526 |                          remote_addr <- resolve "127.0.0.1" "57110"
    |                                         ^^^^^^^

src/Edit.hs:987:27: error:
    Ambiguous occurrence ‘resolve’
    It could refer to
       either ‘Sound.Tidal.Context.resolve’,
              imported from ‘Sound.Tidal.Context’ at src/Edit.hs:30:1-54
              (and originally defined in ‘Sound.Tidal.Stream’)
           or ‘Edit.resolve’, defined at src/Edit.hs:533:1
    |
987 |            remote_addr <- resolve "127.0.0.1" "57110"
    |                           ^^^^^^^
cabal: Leaving directory '.'
cabal: Error: some packages failed to install:
feedforward-0.0.1-1DP1FutITQf9j3PFVRqcEK failed during the building phase. The
exception was:
ExitFailure 1
```

**Comment by ndr-brt** [comment]
Hiding `resolve` fix compilation, but the editor still doesn't work, evaluating `s "bd"` no osc messages are sent to superdirt, and the number `1` on the left have red background.

**Comment by yaxu** [comment]
Hm, is there an error sent to stderr?

**Comment by yaxu** [comment]
I didn't mean to close this, but I just checked and it 'works for me'. We should probably switch the new cVerbose setting to False for feedforward though..

**Comment by ndr-brt** [comment]
I tried to update tidal to 1.7.1 on `feedforward.cabal` and activating cVerbose:
```
tidal <- liftIO $ startTidal (superdirtTarget {oLatency = 0.2, oAddress = "127.0.0.1", oPort = 57120})
              (defaultConfig {cFrameTimespan = 1/20, cVerbose = True})
```
but it doesn't work... I think there's a problem before or while tidal instantiation, will debug it a little

**Comment by yaxu** [comment]
I realised I wasn't on the master branch of feedforward, will try to merge later and see what's up

**Comment by yaxu** [comment]
Ok merged now, and `cabal v1-install` creates a working executable for me

**Comment by ndr-brt** [comment]
the executable is ok, but when I evaluate `s "bd"`, the number on the left becomes red and no osc messages are emitted.
![Screenshot from 2021-02-18 11-26-45](https://user-images.githubusercontent.com/8570990/108343498-4fc53480-71dc-11eb-9fb6-c4d55995fc91.png)

**Comment by yaxu** [comment]
Hm, and no messages to stderr?

**Comment by ndr-brt** [comment]
this is the output:
```
feedforward: sigaction
feedforward: sigaction
Id: 1
```

**Comment by ndr-brt** [comment]
Tried with some logs, it prints a log before this line, but not after:
https://github.com/yaxu/feedforward/blob/06903c93b12903d7d4f8192450da74fe93f3e93a/src/TidalHint.hs#L53

don't know why no error is printed to console

**Comment by ndr-brt** [comment]
ok, the problem is with the `Sound.OSC.Datum` import, without that, everything works... but why?

**Comment by yaxu** [comment]
it might be to do with the usual annoying issues with cabal v2 installs going wrong

**Comment by yaxu** [comment]
I guess OK to close this now but feel free to reopen if there is more to do
