### ISSUE TITLE
Ncurses issue?

### ISSUE THREAD

**Issue by scorchio** [yaxu/feedforward#35]
Hi,

I've been trying to get started with feedforward on macOS (quite old 10.14.6), but following the installation instructions, when I start it, I get into a "somewhat broken" application: e.g. the backspace key enters a control sequence instead of working. This is what I see if I enter `d2 <BACKSPACE><BACKSPACE><BACKSPACE>`:

![Nov-13-2021 14-41-28](https://user-images.githubusercontent.com/236650/141646056-423a52c0-35a0-48e3-a776-688c7947a9a3.gif)

I guess this is possibly because something is off with ncurses, and I was thinking maybe there's a problem with using the Homebrew ncurses, but I might be totally wrong.

**Comment by yaxu** [comment]
Hi @scorchio, probably this is a problem with your terminal. You can find some community support here: https://club.tidalcycles.org/t/getting-experimental-feedforward-editor-to-work/222/23

**Comment by scorchio** [comment]
Thanks for pointing me towards the thread @yaxu. In kitty, `cabal install happy alex` was enough to get things working; Terminal.app required me to set an option for sending Ctrl-H for backspace.
