### ISSUE TITLE
Issue with tidal on 'cabal install'

### ISSUE THREAD

**Issue by liamiepops** [yaxu/feedforward#6]
I'm seeing an issue when running cabal install, which I think might be due to the tidal version I'm using (1.0.6)

```
src/Edit.hs:28:43: error:
    Module ‘Sound.Tidal.Context’ does not export ‘ParamPattern’
   |
28 | import           Sound.Tidal.Context     (ParamPattern, cpsUtils, cpsUtils',
   |                                           ^^^^^^^^^^^^

src/Edit.hs:28:57: error:
    Module ‘Sound.Tidal.Context’ does not export ‘cpsUtils’
   |
28 | import           Sound.Tidal.Context     (ParamPattern, cpsUtils, cpsUtils',
   |                                                         ^^^^^^^^

src/Edit.hs:28:67: error:
    Module ‘Sound.Tidal.Context’ does not export ‘cpsUtils'’
   |
28 | import           Sound.Tidal.Context     (ParamPattern, cpsUtils, cpsUtils',
   |                                                                   ^^^^^^^^^

src/Edit.hs:29:43: error:
    Module ‘Sound.Tidal.Context’ does not export ‘dirtSetters’
   |
29 |                                           dirtSetters, orbit, silence, stack,
   |                                           ^^^^^^^^^^^

src/Edit.hs:30:43: error:
    Module ‘Sound.Tidal.Context’ does not export ‘superDirtSetters’
   |
30 |                                           superDirtSetters, ( # ))
   |                                           ^^^^^^^^^^^^^^^^

```
This feels like the static import object Sound.Tidal.Context has changed, but I can't tell since the package.yaml doesn't specify versions for the dependencies. I'm new to Haskell, so I don't even know if cabal does that kind of thing. Any ideas?

**Comment by yaxu** [comment]
Hi, this is an experimental editor and not really supported as yet, so it might be a bumpy ride..
But I did merge some code in the last few hours that should make it usable with tidal 1.0.6

**Comment by liamiepops** [comment]
Thanks for that, still no joy. I'll have a poke around and see if I can get it running. Cabal doesn't seem to 'containerize' its builds very well. Extra bumpy.

**Comment by yaxu** [comment]
You could try changing into the src folder and running `runhaskell Main 2> err.txt`

**Comment by liamiepops** [comment]
That works if I force tidal 0.x in the .cabal file but not for new tidal. I see you updated TidalHint.hs to use new tidal, but Edit.hs still has the old implementation. It still exposes dirt, etc. I did make some changes to get it working, but I broke most of the editor in the process

**Comment by yaxu** [comment]
Ah I guess I hadn't pushed some changes, sorry. I've just done that now, maybe it helps?

**Comment by liamiepops** [comment]
Yeah it works now. I'm getting an ambiguous method call 'readMaybe' at Edit.hs:491 - I assumed it's Sound.OSC.FD.readMaybe and not Text.Read.readMaybe?

**Comment by yaxu** [comment]
That's odd.. Sound.OSC.FD.readMaybe seems to be imported from Text.Read so not sure what's going on there.
