### ISSUE TITLE
error building. deltaMini not defined

### ISSUE THREAD

**Issue by diegodorado** [yaxu/feedforward#7]
Where is deltaMini defined?
I get this error when I do `cabal install`

`Preprocessing library feedforward-0.0.1...
[1 of 5] Compiling TidalHint        ( src/TidalHint.hs, dist/build/TidalHint.o )

src/TidalHint.hs:70:39: error:
    Variable not in scope: deltaMini :: String -> t
`

**Comment by yaxu** [comment]
@diegodorado That's a tidal function but isn't in the released version, you'll have to build from the github version - master should be fine.

**Comment by diegodorado** [comment]
@yaxu , You mean to install Tidal from source with `cabal install` after cloning the repository?
if so, how do I link that Tidal to this project so it understand `deltaMini`?

**Comment by yaxu** [comment]
@diegodorado Yes, good question! This seems to be very difficult with the new style of cabal install, so I went back to the old one.
Clone tidal and install it from that folder with `cabal v1-update; cabal v1-install`. Then the same install command with feedforward should work.
You might need to remove the 'new-style' package file. If you run `ghci` it will tell you where this file is when it starts.

**Comment by diegodorado** [comment]
I get ` unrecognised command: v1-update`

`cabal-install version 1.24.0.2
compiled using version 1.24.2.0 of the Cabal library 
`

**Comment by yaxu** [comment]
Ah, then you have an old version of haskell/cabal. No problem - `cabal update; cabal install` should work fine in that case

**Comment by diegodorado** [comment]
I am not getting it right... I could install tidal from source, and it istalled tidal version 1.4.6

Now trying to do the same for feedforward, I get this error

```
➜  feedforward git:(master) cabal install
Resolving dependencies...
In order, the following would be installed:
vector-th-unbox-0.2.1.7 (via: math-functions-0.3.3.0) (reinstall) (changes: vector-0.12.0.3 -> 0.12.0.1)
math-functions-0.3.3.0 (via: mwc-random-0.14.0.0) (reinstall) (changes: primitive-0.6.4.0 -> 0.6.2.0, vector-0.12.0.3 -> 0.12.0.1, vector-th-unbox-0.2.1.7 removed)
mwc-random-0.14.0.0 (via: tidal-1.4.5) (reinstall) (changes: math-functions-0.3.3.0 removed, primitive-0.6.4.0 -> 0.6.2.0, vector-0.12.0.3 -> 0.12.0.1)
tidal-1.4.5 (via: feedforward-0.0.1 feedforward-0.0.1) (new version)
feedforward-0.0.1 (new package)
cabal: The following packages are likely to be broken by the reinstalls:
tidal-1.4.6
Use --force-reinstalls if you want to install anyway.
```

**Comment by diegodorado** [comment]
If I run it with `--force-reinstalls` it uses tidal 1.4.5 and get the no deltaMini defined error

**Comment by yaxu** [comment]
Hm, try to pull now. I constrained feedforward to tidal 1.4.6

**Comment by yaxu** [comment]
Otherwise, sometimes the best thing is to remove all the installed libraries and start again. You can do that by removing `~/.cabal` and maybe `~/.ghc`

**Comment by diegodorado** [comment]
Great! it is working now! thank you for the support!, feedforward is a lot of fun!

**Comment by yaxu** [comment]
Nice one!
